version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taskmanager
    restart: unless-stopped
    volumes:
     - data:/var/lib/mysql
    ports:
     - "3360:3306"
